branch-defaults:
  default:
    environment: UsedCarPricePredictNew1
    group_suffix: null
  master:
    environment: null
    group_suffix: null
environment-defaults:
  UsedCarPricePredict:
    branch: null
    repository: null
  UsedCarPricePredictNew1:
    branch: null
    repository: null
global:
  application_name: UsedCarPricePredict
  branch: null
  default_ec2_keyname: prototype1
  default_platform: Python 3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: skumar
  repository: null
  sc: git
  workspace_type: Application
